# example 1: on push to master
name: Bump version
on:
  workflow_call:
    inputs:
      bump_type:
        default: "minor" #other options include: major, and patch
        type: string
        description: "Part of sem-var to bump"
    secrets:
      TOKEN:
        required: true

jobs:
  if: github.ref == 'refs/heads/master'
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          TOKEN: ${{ secrets.TOKEN }}
          WITH_V: true